VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CustomerDetails"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public CustomerName As String
Public CustomerNumber As Integer
Public AccountId As Integer
Public AddressId As Integer
Public Pin As Integer
Public Mobile As String
Public EmailId As String
Public AccountType As String
Public PrivilegeType As String
Public DoorNo As String
Public Street As String
Public City As String
Public State As String
